# ===============================
#  TrendRadar 东莞升学专用配置
#  覆盖原文件即可生效
# ===============================

app:
  # 版本检查：教育场景下建议关闭，防止频繁弹窗
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: false

crawler:
  # 1 秒请求间隔，已足够；教育新闻站点对频率不敏感
  request_interval: 1000
  enable_crawler: true
  use_proxy: false           # 如无境外需求，保持关闭
  default_proxy: "http://127.0.0.1:10086"

report:
  # daily：每天 8 点汇总；incremental：有新增才推
  mode: "daily"
  rank_threshold: 5          # 排名 ≤5 才高亮，降低噪音

notification:
  enable_notification: true
  message_batch_size: 4000
  batch_send_interval: 1
  feishu_message_separator: "━━━━━━━━━━━━━━━━━━━"
  webhooks:
    feishu_url: "${FEISHU_WEBHOOK_URL}"   # 已在 GitHub Secrets
    dingtalk_url: ""
    wework_url: ""
    telegram_bot_token: ""
    telegram_chat_id: ""

# 权重：让「排名」优先，其次「出现频次」，最后「热度」
weight:
  rank_weight: 0.6
  frequency_weight: 0.3
  hotness_weight: 0.1

# ---------- 平台列表 ----------
# 共 40+ 个，把追加的全部整合
platforms:
  # 原有 11
  - id: "toutiao"
    name: "今日头条"
  - id: "baidu"
    name: "百度热搜"
  - id: "wallstreetcn-hot"
    name: "华尔街见闻"
  - id: "thepaper"
    name: "澎湃新闻"
  - id: "bilibili-hot-search"
    name: "bilibili 热搜"
  - id: "cls-hot"
    name: "财联社热门"
  - id: "ifeng"
    name: "凤凰网"
  - id: "tieba"
    name: "贴吧"
  - id: "weibo"
    name: "微博"
  - id: "douyin"
    name: "抖音"
  - id: "zhihu"
    name: "知乎"

  # 追加 30+
  - id: "v2ex"
    name: "V2EX"
  - id: "coolapk"
    name: "酷安"
  - id: "ithome"
    name: "IT之家"
  - id: "pcbeta"
    name: "远景论坛"
  - id: "solidot"
    name: "Solidot"
  - id: "hackernews"
    name: "Hacker News"
  - id: "producthunt"
    name: "Product Hunt"
  - id: "github-trending"
    name: "Github Today"
  - id: "sspai"
    name: "少数派"
  - id: "juejin"
    name: "稀土掘金"
  - id: "zhihu-realtime"
    name: "知乎实时"
  - id: "weibo-realtime"
    name: "微博实时"
  - id: "douyin-realtime"
    name: "抖音实时"
  - id: "hupu"
    name: "虎扑"
  - id: "tieba-hot"
    name: "百度贴吧"
  - id: "toutiao-hot"
    name: "今日头条"
  - id: "thepaper-hot"
    name: "澎湃新闻"
  - id: "bilibili-hot"
    name: "哔哩哔哩"
  - id: "baidu-hot"
    name: "百度热搜"
  - id: "nowcoder"
    name: "牛客"
  - id: "ifeng-hot"
    name: "凤凰网热"
  - id: "chongbuluo"
    name: "虫部落"
  - id: "zaobao"
    name: "联合早报"
  - id: "sputnik"
    name: "卫星通讯社"
  - id: "cankaoxiaoxi"
    name: "参考消息"
  - id: "kaopunews"
    name: "靠谱新闻"
  - id: "mktnews"
    name: "MKTNews"
  - id: "xueqiu"
    name: "雪球"
  - id: "gelonghui"
    name: "格隆汇"
  - id: "fabucaijing"
    name: "法布财经"
